#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export LSCOLORS="gxfxcxdxbxegedabagacad"
export PATH=$HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/bin

export EDITOR=vim
export DEBEMAIL=remi.paulmier@gmail.com
export DEBFULLNAME="Remi Paulmier"

# brew / github API token
export HOMEBREW_GITHUB_API_TOKEN=d70711594d61fff5859140915595420ff31a2849

# chef / knife
export KNIFE_CONF_PATH=${HOME}/.chef/knife.rb

# python3 / pip / virtualenv
# pip should only run if there is a virtualenv currently activated
#export PIP_REQUIRE_VIRTUALENV=true
# virtualenvwrapper
export WORKON_HOME=/Users/remi/.virtualenvs
source /usr/local/bin/virtualenvwrapper_lazy.sh

# Amazon
if test -f $HOME/.local/bin/aws_zsh_completer.sh; then
  source $HOME/.local/bin/aws_zsh_completer.sh
  export PATH=$PATH:$HOME/.local/bin
fi
if test -f $HOME/.aws/config; then
  export AWS_CONFIG_FILE=$HOME/.aws/config
fi

# golang
export GOROOT=/usr/local/go
if test -d $GOROOT/bin; then
    export PATH=$PATH:$GOROOT/bin
fi
export GOPATH=$HOME/gocode
if test -d $GOPATH/bin; then
    export PATH=$PATH:$GOPATH/bin
fi

# rancid
if test -d '/var/lib/rancid/bin'; then
  export PATH="$PATH":/var/lib/rancid/bin
fi
compdef _hosts clogin

# hping
compdef _hosts hping
compdef _hosts hping3

# zsh zle: non-alphanum chars which are part of a word
export WORDCHARS=

# disable shared history
setopt no_share_history

# dont kill bg jobs but still displays a warning at first attempt to exit
# use setopt no_check_jobs if you dont want the 1st check
setopt no_hup

# my aliases
alias rancid='ssh -t rancid@vbbcnetmon1.prod.par-1.h.blbl.cr'
alias lxca='lxc-attach -e -n'
alias s='ssh'
alias sr='ssh -l root'
alias e='emacs'
alias vi='vim'

# zsh completion is case insensitive with prezto
# zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
